import type { ActivoFilaAft } from './types';

export const PALETA_CATEGORIAS = [
  '#2563EB', // Azul corporativo (Equipos)
  '#16A34A', // Verde esmeralda (Mobiliario)
  '#0284C7', // Azul cielo (Vehículos)
  '#D97706', // Ámbar dorado (Herramientas)
  '#7C3AED', // Púrpura (Tecnología / Redes)
  '#64748B', // Pizarra / Otros
];

export const ACTIVOS_AFT_MASTER: ActivoFilaAft[] = [
  {
    id: 'bpi-001',
    codigoQr: 'EQ-000245',
    codigoAft: 'AFT-GEN-2024-001',
    nombre: 'Generador Eléctrico Trifásico 50kVA',
    familia: 'Maquinaria y Equipos',
    subfamilia: 'Generación Eléctrica',
    categoria: 'Equipos',
    marca: 'Caterpillar',
    modelo: 'DE50E0',
    serie: 'CAT-50KVA-88921',
    estado: 'En Servicio',
    direccionNombre: 'Dirección de Operaciones',
    areaNombre: 'Mantenimiento General',
    sedeUbicacion: 'Sede Central - Sala de Máquinas',
    responsableNombre: 'Carlos Vega Miranda',
    rutResponsable: '14.283.910-4',
    valorAdquisicion: 18500000,
    valorLibro: 14800000,
    depreciacionAcumulada: 3700000,
    vidaUtilMeses: 120,
    criticidad: 'Alta',
    tecnologia: 'QR Matriz 2D',
    fechaAlta: '12/03/2024',
    ultimoEscaneo: '16/05/2026',
    veredictoEscaneo: 'Correcto',
    descripcion: 'Generador diésel de emergencia con tablero de transferencia automática y estanque auxiliar de 200L.',
  },
  {
    id: 'bpi-002',
    codigoQr: 'VE-000172',
    codigoAft: 'AFT-VEH-2023-014',
    nombre: 'Camioneta 4x4 Doble Cabina 2.8 TD',
    familia: 'Vehículos y Transporte',
    subfamilia: 'Camionetas Terreno',
    categoria: 'Vehículos',
    marca: 'Toyota',
    modelo: 'Hilux SRV 4x4',
    serie: '8AJBA3CD8E123904',
    estado: 'En Servicio',
    direccionNombre: 'Dirección de Operaciones',
    areaNombre: 'Operaciones en Terreno',
    sedeUbicacion: 'Patio de Maniobras - Estacionamiento 12',
    responsableNombre: 'Rodrigo Morales Castro',
    rutResponsable: '12.894.215-K',
    valorAdquisicion: 26800000,
    valorLibro: 18760000,
    depreciacionAcumulada: 8040000,
    vidaUtilMeses: 84,
    criticidad: 'Alta',
    tecnologia: 'Dual QR/RFID',
    fechaAlta: '05/08/2023',
    ultimoEscaneo: '14/05/2026',
    veredictoEscaneo: 'Correcto',
    descripcion: 'Vehículo operativo con barra antivuelco certificada, GPS institucional y láminas de seguridad.',
  },
  {
    id: 'bpi-003',
    codigoQr: 'MO-000578',
    codigoAft: 'AFT-MOB-2022-089',
    nombre: 'Escritorio Gerencial Ergonométrico en L',
    familia: 'Mobiliario y Útiles',
    subfamilia: 'Puestos de Trabajo',
    categoria: 'Mobiliario',
    marca: 'Masisa / Melamina',
    modelo: 'Executive 180x160',
    serie: 'MOB-ESC-2022-578',
    estado: 'En Servicio',
    direccionNombre: 'Dirección Comercial',
    areaNombre: 'Oficina Director Comercial',
    sedeUbicacion: 'Edificio Corporativo - Piso 2 - Of. 204',
    responsableNombre: 'Andrea Toledo Rivas',
    rutResponsable: '15.932.104-2',
    valorAdquisicion: 480000,
    valorLibro: 288000,
    depreciacionAcumulada: 192000,
    vidaUtilMeses: 60,
    criticidad: 'Baja',
    tecnologia: 'QR Matriz 2D',
    fechaAlta: '20/11/2022',
    ultimoEscaneo: '10/05/2026',
    veredictoEscaneo: 'Correcto',
    descripcion: 'Escritorio ejecutivo con pasacables, faldón metálico y cajonera pedestal móvil de 3 cajones.',
  },
  {
    id: 'bpi-004',
    codigoQr: 'HT-000332',
    codigoAft: 'AFT-HER-2024-045',
    nombre: 'Taladro Industrial Percutor 850W',
    familia: 'Herramientas Industriales',
    subfamilia: 'Herramientas Eléctricas',
    categoria: 'Herramientas',
    marca: 'Bosch Professional',
    modelo: 'GSB 16 RE',
    serie: 'BSH-992014-98',
    estado: 'En Servicio',
    direccionNombre: 'Dirección de Operaciones',
    areaNombre: 'Taller Mecánico Central',
    sedeUbicacion: 'Taller Central - Banco 4',
    responsableNombre: 'Felipe Soto Guzmán',
    rutResponsable: '16.741.092-8',
    valorAdquisicion: 145000,
    valorLibro: 116000,
    depreciacionAcumulada: 29000,
    vidaUtilMeses: 36,
    criticidad: 'Media',
    tecnologia: 'QR Matriz 2D',
    fechaAlta: '15/01/2024',
    ultimoEscaneo: '08/05/2026',
    veredictoEscaneo: 'Correcto',
    descripcion: 'Herramienta con mandril de 13mm, control de velocidad variable y maletín de transporte con set de brocas.',
  },
  {
    id: 'bpi-005',
    codigoQr: 'EQ-000891',
    codigoAft: 'AFT-TI-2023-003',
    nombre: 'Servidor Rack 2U Dell PowerEdge R740',
    familia: 'Tecnología e Informática',
    subfamilia: 'Servidores e Infraestructura',
    categoria: 'Equipos',
    marca: 'Dell EMC',
    modelo: 'PowerEdge R740',
    serie: 'SVC-TAG-9X882K',
    estado: 'En Mantenimiento',
    direccionNombre: 'Dirección de Tecnología',
    areaNombre: 'Data Center y Servidores',
    sedeUbicacion: 'Sede Central - Data Center - Rack A4',
    responsableNombre: 'Mauricio Díaz Parra',
    rutResponsable: '13.450.812-7',
    valorAdquisicion: 8900000,
    valorLibro: 5340000,
    depreciacionAcumulada: 3560000,
    vidaUtilMeses: 48,
    criticidad: 'Alta',
    tecnologia: 'Dual QR/RFID',
    fechaAlta: '18/06/2023',
    ultimoEscaneo: '05/05/2026',
    veredictoEscaneo: 'Observado',
    descripcion: 'Dual Intel Xeon Gold 6230, 128GB RAM DDR4 ECC, arreglo RAID 10 4x1.92TB NVMe SSD.',
  },
  {
    id: 'bpi-006',
    codigoQr: 'MO-000112',
    codigoAft: 'AFT-MOB-2020-019',
    nombre: 'Silla Operativa Anatómica Mesh',
    familia: 'Mobiliario y Útiles',
    subfamilia: 'Sillería de Oficina',
    categoria: 'Mobiliario',
    marca: 'ErgoClass',
    modelo: 'Comfort Mesh Pro',
    serie: 'SL-2020-0112',
    estado: 'Baja',
    direccionNombre: 'Dirección de Administración',
    areaNombre: 'Bodega de Rezago',
    sedeUbicacion: 'Sede Norte - Bodega B3',
    responsableNombre: 'Sin Asignar',
    rutResponsable: '—',
    valorAdquisicion: 165000,
    valorLibro: 0,
    depreciacionAcumulada: 165000,
    vidaUtilMeses: 36,
    criticidad: 'Baja',
    tecnologia: 'QR Matriz 2D',
    fechaAlta: '14/02/2020',
    ultimoEscaneo: '02/05/2026',
    veredictoEscaneo: 'Pendiente',
    descripcion: 'Mecanismo sincrónico roto y pistón neumático sin retención. Propuesta de baja técnica.',
  },
  {
    id: 'bpi-007',
    codigoQr: 'VE-000045',
    codigoAft: 'AFT-VEH-2022-005',
    nombre: 'Furgón Logístico Reparto 13m3',
    familia: 'Vehículos y Transporte',
    subfamilia: 'Furgones de Carga',
    categoria: 'Vehículos',
    marca: 'Peugeot',
    modelo: 'Boxer L3H2 HDi',
    serie: 'VF3YCTMFC129841',
    estado: 'Traslado',
    direccionNombre: 'Dirección de Logística',
    areaNombre: 'Transporte y Distribución',
    sedeUbicacion: 'En Tránsito: Santiago - Valparaíso',
    responsableNombre: 'Víctor Alarcón Silva',
    rutResponsable: '11.590.234-5',
    valorAdquisicion: 22400000,
    valorLibro: 13440000,
    depreciacionAcumulada: 8960000,
    vidaUtilMeses: 84,
    criticidad: 'Alta',
    tecnologia: 'Dual QR/RFID',
    fechaAlta: '10/09/2022',
    ultimoEscaneo: '29/04/2026',
    veredictoEscaneo: 'Correcto',
    descripcion: 'Furgón carrozado con termógrafo digital y plataforma hidráulica de carga.',
  },
  {
    id: 'bpi-008',
    codigoQr: 'HT-000674',
    codigoAft: 'AFT-HER-2023-091',
    nombre: 'Sierra Circular Banco 2000W 10"',
    familia: 'Herramientas Industriales',
    subfamilia: 'Corte y Aserrado',
    categoria: 'Herramientas',
    marca: 'Makita',
    modelo: 'MLT100N',
    serie: 'MKT-884102-09',
    estado: 'En Mantenimiento',
    direccionNombre: 'Dirección de Operaciones',
    areaNombre: 'Taller de Carpintería',
    sedeUbicacion: 'Sede Industrial - Taller Mueblería',
    responsableNombre: 'Gonzalo Silva Bravo',
    rutResponsable: '15.112.784-9',
    valorAdquisicion: 560000,
    valorLibro: 392000,
    depreciacionAcumulada: 168000,
    vidaUtilMeses: 48,
    criticidad: 'Media',
    tecnologia: 'QR Matriz 2D',
    fechaAlta: '18/04/2023',
    ultimoEscaneo: '25/04/2026',
    veredictoEscaneo: 'Observado',
    descripcion: 'Sierra de mesa para disco de 255mm con mesa extensible y guía paralela.',
  },
];
