// Catálogo oficial completo de los 60 activos fijos de la DIRECCIÓN GENERAL
// (EMPRESA SUCHEL TROPICAL) extraídos de la hoja Excel "CU-PAT-DIRECCION-GENERAL-completo".
import type { Product } from './db';

export const FULL_CATALOG: Product[] = [
  {
    code: 'QR-DG-001',
    codigoAft: 'DG-001',
    name: 'MESA BURO/ 4 GAVETAS',
    description: 'MESA BURO/ 4 GAVETAS en OFICINA DIRECTOR GENERAL (AFT: DG-001, Categoría: MOBILIARIO).',
    organizationId: 'org-001',
    areaId: 'area-001',
    locationId: 'loc-001',
  },
  {
    code: 'QR-DG-002',
    codigoAft: 'DG-002',
    name: 'SILLA GIRATORIA',
    description: 'SILLA GIRATORIA en OFICINA DIRECTOR GENERAL (AFT: DG-002, Categoría: MOBILIARIO).',
    organizationId: 'org-001',
    areaId: 'area-001',
    locationId: 'loc-001',
  },
  {
    code: 'QR-DG-003',
    codigoAft: 'DG-003',
    name: 'PC ESCRITORIO',
    description: 'PC ESCRITORIO en OFICINA DIRECTOR GENERAL (AFT: DG-003, Categoría: INFORMATICA).',
    organizationId: 'org-001',
    areaId: 'area-001',
    locationId: 'loc-001',
  },
  {
    code: 'QR-DG-004',
    codigoAft: 'DG-004',
    name: 'IMPRESORA',
    description: 'IMPRESORA en OFICINA DIRECTOR GENERAL (AFT: DG-004, Categoría: INFORMATICA).',
    organizationId: 'org-001',
    areaId: 'area-001',
    locationId: 'loc-001',
  },
  {
    code: 'QR-DG-005',
    codigoAft: 'DG-005',
    name: 'EQUIPO CLIMATIZACION 12000 BTU',
    description: 'EQUIPO CLIMATIZACION 12000 BTU en OFICINA DIRECTOR GENERAL (AFT: DG-005, Categoría: EQUIPOS DE CLIMATIZACION Y REFRIGERACION).',
    organizationId: 'org-001',
    areaId: 'area-001',
    locationId: 'loc-002',
  },
  {
    code: 'QR-DG-006',
    codigoAft: 'DG-006',
    name: 'SOFA 3 PERONAS',
    description: 'SOFA 3 PERONAS en OFICINA DIRECTOR GENERAL (AFT: DG-006, Categoría: MOBILIARIO).',
    organizationId: 'org-001',
    areaId: 'area-001',
    locationId: 'loc-002',
  },
  {
    code: 'QR-DG-007',
    codigoAft: 'DG-007',
    name: 'BUTACA CON BRAZOS',
    description: 'BUTACA CON BRAZOS en OFICINA DIRECTOR GENERAL (AFT: DG-007, Categoría: MOBILIARIO).',
    organizationId: 'org-001',
    areaId: 'area-001',
    locationId: 'loc-002',
  },
  {
    code: 'QR-DG-008',
    codigoAft: 'DG-008',
    name: 'BUTACA CON BRAZOS',
    description: 'BUTACA CON BRAZOS en OFICINA DIRECTOR GENERAL (AFT: DG-008, Categoría: MOBILIARIO).',
    organizationId: 'org-001',
    areaId: 'area-002',
    locationId: 'loc-001',
  },
  {
    code: 'QR-DG-009',
    codigoAft: 'DG-009',
    name: 'BUTACA CON BRAZOS',
    description: 'BUTACA CON BRAZOS en OFICINA DIRECTOR GENERAL (AFT: DG-009, Categoría: MOBILIARIO).',
    organizationId: 'org-001',
    areaId: 'area-002',
    locationId: 'loc-001',
  },
  {
    code: 'QR-DG-010',
    codigoAft: 'DG-010',
    name: 'TV DIGITAL LG 45"',
    description: 'TV DIGITAL LG 45" en OFICINA DIRECTOR GENERAL (AFT: DG-010, Categoría: MOBILIARIO).',
    organizationId: 'org-002',
    areaId: 'area-001',
    locationId: 'loc-001',
  },
  {
    code: 'QR-DG-011',
    codigoAft: 'DG-011',
    name: 'LAPTOP',
    description: 'LAPTOP en OFICINA DIRECTOR GENERAL (AFT: DG-011, Categoría: INFORMATICA).',
    organizationId: 'org-002',
    areaId: 'area-001',
    locationId: 'loc-001',
  },
  {
    code: 'QR-DG-012',
    codigoAft: 'DG-012',
    name: 'MESA BURO/ 4 GAVETAS',
    description: 'MESA BURO/ 4 GAVETAS en OFICINA SECRETARIA EJECUTIVA (AFT: DG-012, Categoría: MOBILIARIO).',
    organizationId: 'org-002',
    areaId: 'area-001',
    locationId: 'loc-001',
  },
  {
    code: 'QR-DG-013',
    codigoAft: 'DG-013',
    name: 'SILLA GIRATORIA',
    description: 'SILLA GIRATORIA en OFICINA SECRETARIA EJECUTIVA (AFT: DG-013, Categoría: MOBILIARIO).',
    organizationId: 'org-002',
    areaId: 'area-001',
    locationId: 'loc-001',
  },
  {
    code: 'QR-DG-014',
    codigoAft: 'DG-014',
    name: 'PC ESCRITORIO',
    description: 'PC ESCRITORIO en OFICINA SECRETARIA EJECUTIVA (AFT: DG-014, Categoría: INFORMATICA).',
    organizationId: 'org-002',
    areaId: 'area-001',
    locationId: 'loc-001',
  },
  {
    code: 'QR-DG-015',
    codigoAft: 'DG-015',
    name: 'IMPRESORA',
    description: 'IMPRESORA en OFICINA SECRETARIA EJECUTIVA (AFT: DG-015, Categoría: INFORMATICA).',
    organizationId: 'org-002',
    areaId: 'area-001',
    locationId: 'loc-001',
  },
  {
    code: 'QR-DG-016',
    codigoAft: 'DG-016',
    name: 'VENTILADOR',
    description: 'VENTILADOR en OFICINA SECRETARIA EJECUTIVA (AFT: DG-016, Categoría: CLIMATIZACION Y REFRIGERACION).',
    organizationId: 'org-002',
    areaId: 'area-002',
    locationId: 'loc-002',
  },
  {
    code: 'QR-DG-017',
    codigoAft: 'DG-017',
    name: 'BUTACA CON BRAZOS',
    description: 'BUTACA CON BRAZOS en OFICINA SECRETARIA EJECUTIVA (AFT: DG-017, Categoría: MOBILIARIO).',
    organizationId: 'org-002',
    areaId: 'area-002',
    locationId: 'loc-002',
  },
  {
    code: 'QR-DG-018',
    codigoAft: 'DG-018',
    name: 'BUTACA CON BRAZOS',
    description: 'BUTACA CON BRAZOS en OFICINA SECRETARIA EJECUTIVA (AFT: DG-018, Categoría: MOBILIARIO).',
    organizationId: 'org-002',
    areaId: 'area-002',
    locationId: 'loc-002',
  },
  {
    code: 'QR-DG-019',
    codigoAft: 'DG-019',
    name: 'CREDENZA 4 GAVETAS, METALICA',
    description: 'CREDENZA 4 GAVETAS, METALICA en OFICINA SECRETARIA EJECUTIVA (AFT: DG-019, Categoría: MOBILIARIO).',
    organizationId: 'org-002',
    areaId: 'area-002',
    locationId: 'loc-002',
  },
  {
    code: 'QR-DG-020',
    codigoAft: 'DG-020',
    name: 'MESA REUNIONES 12 PLAZAS',
    description: 'MESA REUNIONES 12 PLAZAS en SALON REUNIONES (AFT: DG-020, Categoría: MOBILIARIO).',
    organizationId: 'org-002',
    areaId: 'area-003',
    locationId: 'loc-003',
  },
  {
    code: 'QR-DG-021',
    codigoAft: 'DG-021',
    name: 'SILLA',
    description: 'SILLA en SALON REUNIONES (AFT: DG-021, Categoría: MOBILIARIO).',
    organizationId: 'org-002',
    areaId: 'area-003',
    locationId: 'loc-003',
  },
  {
    code: 'QR-DG-022',
    codigoAft: 'DG-022',
    name: 'SILLA',
    description: 'SILLA en SALON REUNIONES (AFT: DG-022, Categoría: MOBILIARIO).',
    organizationId: 'org-002',
    areaId: 'area-003',
    locationId: 'loc-003',
  },
  {
    code: 'QR-DG-023',
    codigoAft: 'DG-023',
    name: 'SILLA',
    description: 'SILLA en SALON REUNIONES (AFT: DG-023, Categoría: MOBILIARIO).',
    organizationId: 'org-002',
    areaId: 'area-003',
    locationId: 'loc-003',
  },
  {
    code: 'QR-DG-024',
    codigoAft: 'DG-024',
    name: 'SILLA',
    description: 'SILLA en SALON REUNIONES (AFT: DG-024, Categoría: MOBILIARIO).',
    organizationId: 'org-002',
    areaId: 'area-003',
    locationId: 'loc-003',
  },
  {
    code: 'QR-DG-025',
    codigoAft: 'DG-025',
    name: 'SILLA',
    description: 'SILLA en SALON REUNIONES (AFT: DG-025, Categoría: MOBILIARIO).',
    organizationId: 'org-002',
    areaId: 'area-003',
    locationId: 'loc-003',
  },
  {
    code: 'QR-DG-026',
    codigoAft: 'DG-026',
    name: 'SILLA',
    description: 'SILLA en SALON REUNIONES (AFT: DG-026, Categoría: MOBILIARIO).',
    organizationId: 'org-002',
    areaId: 'area-003',
    locationId: 'loc-003',
  },
  {
    code: 'QR-DG-027',
    codigoAft: 'DG-027',
    name: 'SILLA',
    description: 'SILLA en SALON REUNIONES (AFT: DG-027, Categoría: MOBILIARIO).',
    organizationId: 'org-002',
    areaId: 'area-003',
    locationId: 'loc-003',
  },
  {
    code: 'QR-DG-028',
    codigoAft: 'DG-028',
    name: 'SILLA',
    description: 'SILLA en SALON REUNIONES (AFT: DG-028, Categoría: MOBILIARIO).',
    organizationId: 'org-002',
    areaId: 'area-003',
    locationId: 'loc-003',
  },
  {
    code: 'QR-DG-029',
    codigoAft: 'DG-029',
    name: 'SILLA',
    description: 'SILLA en SALON REUNIONES (AFT: DG-029, Categoría: MOBILIARIO).',
    organizationId: 'org-002',
    areaId: 'area-003',
    locationId: 'loc-003',
  },
  {
    code: 'QR-DG-030',
    codigoAft: 'DG-030',
    name: 'SILLA',
    description: 'SILLA en SALON REUNIONES (AFT: DG-030, Categoría: MOBILIARIO).',
    organizationId: 'org-002',
    areaId: 'area-003',
    locationId: 'loc-003',
  },
  {
    code: 'QR-DG-031',
    codigoAft: 'DG-031',
    name: 'SILLA',
    description: 'SILLA en SALON REUNIONES (AFT: DG-031, Categoría: MOBILIARIO).',
    organizationId: 'org-002',
    areaId: 'area-003',
    locationId: 'loc-003',
  },
  {
    code: 'QR-DG-032',
    codigoAft: 'DG-032',
    name: 'SILLA',
    description: 'SILLA en SALON REUNIONES (AFT: DG-032, Categoría: MOBILIARIO).',
    organizationId: 'org-002',
    areaId: 'area-003',
    locationId: 'loc-003',
  },
  {
    code: 'QR-DG-033',
    codigoAft: 'DG-033',
    name: 'EQUIPO DE CLIMATIZACION 24000 BTU',
    description: 'EQUIPO DE CLIMATIZACION 24000 BTU en SALON REUNIONES (AFT: DG-033, Categoría: EQUIPOS DE CLIMATIZACION Y REFRIGERACION).',
    organizationId: 'org-002',
    areaId: 'area-003',
    locationId: 'loc-003',
  },
  {
    code: 'QR-DG-034',
    codigoAft: 'DG-034',
    name: 'TV DIGITAL 54"',
    description: 'TV DIGITAL 54" en SALON REUNIONES (AFT: DG-034, Categoría: MOBILIARIO).',
    organizationId: 'org-002',
    areaId: 'area-003',
    locationId: 'loc-003',
  },
  {
    code: 'QR-DG-035',
    codigoAft: 'DG-035',
    name: 'VIDEO BEAM',
    description: 'VIDEO BEAM en SALON REUNIONES (AFT: DG-035, Categoría: INFORMATICA).',
    organizationId: 'org-002',
    areaId: 'area-003',
    locationId: 'loc-003',
  },
  {
    code: 'QR-DG-036',
    codigoAft: 'DG-036',
    name: 'PANTALLA VIDEO BEAM',
    description: 'PANTALLA VIDEO BEAM en SALON REUNIONES (AFT: DG-036, Categoría: INFORMATICA).',
    organizationId: 'org-002',
    areaId: 'area-003',
    locationId: 'loc-003',
  },
  {
    code: 'QR-DG-037',
    codigoAft: 'DG-037',
    name: 'VENTILADOR',
    description: 'VENTILADOR en SALON REUNIONES (AFT: DG-037, Categoría: EQUIPOS DE CLIMATIZACION Y REFRIGERACION).',
    organizationId: 'org-002',
    areaId: 'area-003',
    locationId: 'loc-003',
  },
  {
    code: 'QR-DG-038',
    codigoAft: 'DG-038',
    name: 'VENTILADOR',
    description: 'VENTILADOR en SALON REUNIONES (AFT: DG-038, Categoría: EQUIPOS DE CLIMATIZACION Y REFRIGERACION).',
    organizationId: 'org-002',
    areaId: 'area-003',
    locationId: 'loc-003',
  },
  {
    code: 'QR-DG-039',
    codigoAft: 'DG-039',
    name: 'VENTILADOR',
    description: 'VENTILADOR en SALON REUNIONES (AFT: DG-039, Categoría: EQUIPOS DE CLIMATIZACION Y REFRIGERACION).',
    organizationId: 'org-002',
    areaId: 'area-003',
    locationId: 'loc-003',
  },
  {
    code: 'QR-DG-040',
    codigoAft: 'DG-040',
    name: 'VENTILADOR',
    description: 'VENTILADOR en SALON REUNIONES (AFT: DG-040, Categoría: EQUIPOS DE CLIMATIZACION Y REFRIGERACION).',
    organizationId: 'org-002',
    areaId: 'area-003',
    locationId: 'loc-003',
  },
  {
    code: 'QR-DG-041',
    codigoAft: 'DG-041',
    name: 'MESA BURO/ 4 GAVETAS',
    description: 'MESA BURO/ 4 GAVETAS en JURIDICO (AFT: DG-041, Categoría: MOBILIARIO).',
    organizationId: 'org-002',
    areaId: 'area-004',
    locationId: 'loc-004',
  },
  {
    code: 'QR-DG-042',
    codigoAft: 'DG-042',
    name: 'MESA BURO/ 4 GAVETAS',
    description: 'MESA BURO/ 4 GAVETAS en JURIDICO (AFT: DG-042, Categoría: MOBILIARIO).',
    organizationId: 'org-002',
    areaId: 'area-004',
    locationId: 'loc-004',
  },
  {
    code: 'QR-DG-043',
    codigoAft: 'DG-043',
    name: 'SILLA GIRATORIA',
    description: 'SILLA GIRATORIA en JURIDICO (AFT: DG-043, Categoría: MOBILIARIO).',
    organizationId: 'org-002',
    areaId: 'area-004',
    locationId: 'loc-004',
  },
  {
    code: 'QR-DG-044',
    codigoAft: 'DG-044',
    name: 'SILLA GIRATORIA',
    description: 'SILLA GIRATORIA en JURIDICO (AFT: DG-044, Categoría: MOBILIARIO).',
    organizationId: 'org-002',
    areaId: 'area-004',
    locationId: 'loc-004',
  },
  {
    code: 'QR-DG-045',
    codigoAft: 'DG-045',
    name: 'VENTILADOR',
    description: 'VENTILADOR en JURIDICO (AFT: DG-045, Categoría: EQUIPOS DE CLIMATIZACION Y REFRIGERACION).',
    organizationId: 'org-002',
    areaId: 'area-004',
    locationId: 'loc-004',
  },
  {
    code: 'QR-DG-046',
    codigoAft: 'DG-046',
    name: 'VENTILADOR',
    description: 'VENTILADOR en JURIDICO (AFT: DG-046, Categoría: EQUIPOS DE CLIMATIZACION Y REFRIGERACION).',
    organizationId: 'org-002',
    areaId: 'area-004',
    locationId: 'loc-004',
  },
  {
    code: 'QR-DG-047',
    codigoAft: 'DG-047',
    name: 'PC ESCRITORIO',
    description: 'PC ESCRITORIO en JURIDICO (AFT: DG-047, Categoría: INFORMATICA).',
    organizationId: 'org-002',
    areaId: 'area-004',
    locationId: 'loc-004',
  },
  {
    code: 'QR-DG-048',
    codigoAft: 'DG-048',
    name: 'PC ESCRITORIO',
    description: 'PC ESCRITORIO en JURIDICO (AFT: DG-048, Categoría: MOBILIARIO).',
    organizationId: 'org-002',
    areaId: 'area-004',
    locationId: 'loc-004',
  },
  {
    code: 'QR-DG-049',
    codigoAft: 'DG-049',
    name: 'IMPRESORA',
    description: 'IMPRESORA en JURIDICO (AFT: DG-049, Categoría: INFORMATICA).',
    organizationId: 'org-002',
    areaId: 'area-004',
    locationId: 'loc-004',
  },
  {
    code: 'QR-DG-050',
    codigoAft: 'DG-050',
    name: 'REFRIGERADOR',
    description: 'REFRIGERADOR en PANTRY (AFT: DG-050, Categoría: EQUIPOS DE CLIMATIZACION Y REFRIGERACION).',
    organizationId: 'org-002',
    areaId: 'area-005',
    locationId: 'loc-005',
  },
  {
    code: 'QR-DG-051',
    codigoAft: 'DG-051',
    name: 'FREEZER',
    description: 'FREEZER en PANTRY (AFT: DG-051, Categoría: EQUIPOS DE CLIMATIZACION Y REFRIGERACION).',
    organizationId: 'org-002',
    areaId: 'area-005',
    locationId: 'loc-005',
  },
  {
    code: 'QR-DG-052',
    codigoAft: 'DG-052',
    name: 'CAFETERA',
    description: 'CAFETERA en PANTRY (AFT: DG-052, Categoría: ELECTRODOMESTICOS).',
    organizationId: 'org-002',
    areaId: 'area-005',
    locationId: 'loc-005',
  },
  {
    code: 'QR-DG-053',
    codigoAft: 'DG-053',
    name: 'HORNO MICROWAVE',
    description: 'HORNO MICROWAVE en PANTRY (AFT: DG-053, Categoría: ELECTRODOMESTICOS).',
    organizationId: 'org-002',
    areaId: 'area-005',
    locationId: 'loc-005',
  },
  {
    code: 'QR-DG-054',
    codigoAft: 'DG-054',
    name: 'BATIDORA',
    description: 'BATIDORA en PANTRY (AFT: DG-054, Categoría: ELECTRODOMESTICOS).',
    organizationId: 'org-002',
    areaId: 'area-005',
    locationId: 'loc-005',
  },
  {
    code: 'QR-DG-055',
    codigoAft: 'DG-055',
    name: 'MESA 4 PERSONAS',
    description: 'MESA 4 PERSONAS en PANTRY (AFT: DG-055, Categoría: MOBILIARIO).',
    organizationId: 'org-002',
    areaId: 'area-005',
    locationId: 'loc-005',
  },
  {
    code: 'QR-DG-056',
    codigoAft: 'DG-056',
    name: 'SILLA',
    description: 'SILLA en PANTRY (AFT: DG-056, Categoría: MOBILIARIO).',
    organizationId: 'org-002',
    areaId: 'area-005',
    locationId: 'loc-005',
  },
  {
    code: 'QR-DG-057',
    codigoAft: 'DG-057',
    name: 'SILLA',
    description: 'SILLA en PANTRY (AFT: DG-057, Categoría: MOBILIARIO).',
    organizationId: 'org-002',
    areaId: 'area-005',
    locationId: 'loc-005',
  },
  {
    code: 'QR-DG-058',
    codigoAft: 'DG-058',
    name: 'SILLA',
    description: 'SILLA en PANTRY (AFT: DG-058, Categoría: MOBILIARIO).',
    organizationId: 'org-002',
    areaId: 'area-005',
    locationId: 'loc-005',
  },
  {
    code: 'QR-DG-059',
    codigoAft: 'DG-059',
    name: 'SILLA',
    description: 'SILLA en PANTRY (AFT: DG-059, Categoría: MOBILIARIO).',
    organizationId: 'org-002',
    areaId: 'area-005',
    locationId: 'loc-005',
  },
  {
    code: 'QR-DG-060',
    codigoAft: 'DG-060',
    name: 'VENTILADOR',
    description: 'VENTILADOR en PANTRY (AFT: DG-060, Categoría: EQUIPOS DE CLIMATIZACION Y REFRIGERACION).',
    organizationId: 'org-002',
    areaId: 'area-005',
    locationId: 'loc-005',
  },
];

export const REGISTERED_CODES: string[] = FULL_CATALOG.slice(0, 15).map((p) => p.code);
